apiVersion: v1
kind: ConfigMap
metadata:
  name: config-watcher-demo
  namespace: backend
data:
  application.yml: |-
    server:
      port: 8090
      servlet:
        context-path: /config-watcher-demo
    management:
      endpoints:
        web:
          exposure:
            include: [
                prometheus,
                health,
                info,
                refresh,
                bus-refresh,
                beans,
                env
            ]
