# template for config-watcher-demo-storage-connections-Secret with Spring Cloud Kubernetes Configuration Watcher enabled
apiVersion: v1
kind: Secret
metadata:
  labels:
    spring.cloud.kubernetes.secret: "true"
  name: demo-secret2
  namespace: backend
data:
  storageconnections.test: YXNkZgo=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    spring.cloud.kubernetes.secret: "true"
  name: demo-secret1
  namespace: backend
data:
  something: YXNkZgo=
type: Opaque
