apiVersion: v1
kind: ServiceAccount
metadata:
 name: config-watcher-demo-account
 namespace: backend
---
# hack -> clusteradmin
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-watcher-demo-namespace-reader-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: config-watcher-demo-account
    namespace: backend
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""